// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Item in *Clinician → Focuses*
 */
export interface ClinicianDocumentDataFocusesItem {
  /**
   * Focus field in *Clinician → Focuses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a focus
   * - **API ID Path**: clinician.focuses[].focus
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  focus: prismic.KeyTextField
}

/**
 * Item in *Clinician → Approaches*
 */
export interface ClinicianDocumentDataApproachesItem {
  /**
   * Approach field in *Clinician → Approaches*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.approaches[].approach
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  approach: prismic.KeyTextField
}

/**
 * Item in *Clinician → Services*
 */
export interface ClinicianDocumentDataServicesItem {
  /**
   * Service field in *Clinician → Services*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.services[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<'service'>
}

type ClinicianDocumentDataSlicesSlice =
  | ProcessSlice
  | ImageWithTextSlice
  | FeaturingSlice
  | RichTextSlice

/**
 * Content for Clinician documents
 */
interface ClinicianDocumentData {
  /**
   * Full Name field in *Clinician*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the clinician's full name
   * - **API ID Path**: clinician.full_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  full_name: prismic.TitleField

  /**
   * First Name field in *Clinician*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.first_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name: prismic.KeyTextField

  /**
   * Portrait field in *Clinician*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.portrait
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portrait: prismic.ImageField<never>

  /**
   * Status field in *Clinician*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<
    | 'Accepting New Clients'
    | 'Waitlist for New Clients'
    | 'Not Accepting New Clients'
  >

  /**
   * Service Delivery field in *Clinician*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.service_delivery
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  service_delivery: prismic.SelectField<'Telehealth' | 'In Person' | 'Hybrid'>

  /**
   * Focuses field in *Clinician*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.focuses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  focuses: prismic.GroupField<Simplify<ClinicianDocumentDataFocusesItem>>

  /**
   * Approaches field in *Clinician*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.approaches[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  approaches: prismic.GroupField<Simplify<ClinicianDocumentDataApproachesItem>>

  /**
   * About field in *Clinician*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a description of the clinician
   * - **API ID Path**: clinician.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField

  /**
   * Services field in *Clinician*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.services[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<Simplify<ClinicianDocumentDataServicesItem>>

  /**
   * Specialties field in *Clinician*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Make a list of specialties
   * - **API ID Path**: clinician.specialties
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  specialties: prismic.RichTextField

  /**
   * Psychtoday field in *Clinician*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.psychtoday
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  psychtoday: prismic.LinkField

  /**
   * Slice Zone field in *Clinician*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClinicianDocumentDataSlicesSlice> /**
   * Meta Description field in *Clinician*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clinician.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Clinician*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clinician.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Clinician*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clinician.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Clinician document from Prismic
 *
 * - **API ID**: `clinician`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClinicianDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClinicianDocumentData>,
    'clinician',
    Lang
  >

type FooterDocumentDataSlicesSlice =
  | ContactInfoSlice
  | LinkListSlice
  | FooterLogoSlice

type FooterDocumentDataSlices1Slice =
  | FooterLogoSlice
  | LinkListSlice
  | ContactInfoSlice

type FooterDocumentDataSlices2Slice =
  | LinkListSlice
  | FooterLogoSlice
  | ContactInfoSlice

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<FooterDocumentDataSlices1Slice> /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<FooterDocumentDataSlices2Slice>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, 'footer', Lang>

type HomepageDocumentDataSlicesSlice =
  | ProcessSlice
  | ImageWithTextSlice
  | FeaturingSlice
  | RichTextSlice
  | HeroSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type LayoutDocumentDataSlicesSlice = MenuItemSlice

type LayoutDocumentDataSlices1Slice = FooterElementSlice

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * CTA Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField

  /**
   * CTA Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta_link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * Logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice> /**
   * Privacy Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_label
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy_label: prismic.KeyTextField

  /**
   * Privacy Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_link: prismic.LinkField

  /**
   * Copyright Text field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copyright_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright_text: prismic.KeyTextField

  /**
   * Footer CTA field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_cta
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_cta: prismic.KeyTextField

  /**
   * Footer CTA Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_cta_label
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_cta_label: prismic.KeyTextField

  /**
   * Footer CTA Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_cta_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_cta_link: prismic.LinkField

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<LayoutDocumentDataSlices1Slice>
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    'layout',
    Lang
  >

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | MapWithDetailsSlice
  | ProcessSlice
  | ImageWithTextSlice
  | FeaturingSlice
  | ContentIndexSlice
  | RichTextSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

type ServiceDocumentDataSlicesSlice =
  | ProcessSlice
  | ServiceTargetSlice
  | RichTextSlice

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe the service
   * - **API ID Path**: service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, 'service', Lang>

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Domain field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.domain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  domain: prismic.KeyTextField

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField

  /**
   * Site Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_meta_description: prismic.KeyTextField

  /**
   * Site Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_meta_image: prismic.ImageField<never>
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

type SubMenuDocumentDataSlicesSlice = SubMenuHeadingSlice | SubMenuItemSlice

type SubMenuDocumentDataSlices1Slice = SubMenuHeadingSlice | SubMenuItemSlice

type SubMenuDocumentDataSlices2Slice = SubMenuHeadingSlice | SubMenuItemSlice

/**
 * Content for Sub Menu documents
 */
interface SubMenuDocumentData {
  /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuDocumentDataSlicesSlice> /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<SubMenuDocumentDataSlices1Slice> /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<SubMenuDocumentDataSlices2Slice>
}

/**
 * Sub Menu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubMenuDocumentData>,
    'sub_menu',
    Lang
  >

export type AllDocumentTypes =
  | ClinicianDocument
  | FooterDocument
  | HomepageDocument
  | LayoutDocument
  | PageDocument
  | ServiceDocument
  | SettingsDocument
  | SubMenuDocument

/**
 * Primary content in *ContactInfo → Default → Primary*
 */
export interface ContactInfoSliceDefaultPrimary {
  /**
   * Heading field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Details field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField
}

/**
 * Default variation for ContactInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactInfoSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ContactInfo*
 */
type ContactInfoSliceVariation = ContactInfoSliceDefault

/**
 * ContactInfo Shared Slice
 *
 * - **API ID**: `contact_info`
 * - **Description**: ContactInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSlice = prismic.SharedSlice<
  'contact_info',
  ContactInfoSliceVariation
>

/**
 * Primary content in *ContentIndex → Default → Primary*
 */
export interface ContentIndexSliceDefaultPrimary {
  /**
   * Content Type field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.content_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_type: prismic.SelectField<'clinician' | 'service'>

  /**
   * Content CTA Text field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.content_cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_cta_text: prismic.KeyTextField

  /**
   * Fallback Item Image field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.fallback_item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_item_image: prismic.ImageField<never>

  /**
   * Number To Display field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.number_to_display
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number_to_display: prismic.NumberField
}

/**
 * Default variation for ContentIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentIndexSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentIndexSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ContentIndex*
 */
type ContentIndexSliceVariation = ContentIndexSliceDefault

/**
 * ContentIndex Shared Slice
 *
 * - **API ID**: `content_index`
 * - **Description**: ContentIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentIndexSlice = prismic.SharedSlice<
  'content_index',
  ContentIndexSliceVariation
>

/**
 * Item in *Featuring → Default → Primary → Features*
 */
export interface FeaturingSliceDefaultPrimaryFeaturesItem {
  /**
   * Image field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Feature Heading field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].feature_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading: prismic.RichTextField

  /**
   * Feature Description field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField

  /**
   * Button Label field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Alt field in *Featuring → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[].button_alt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_alt: prismic.KeyTextField
}

/**
 * Item in *Featuring → No Image → Primary → Features*
 */
export interface FeaturingSliceNoImagePrimaryFeaturesItem {
  /**
   * Feature Heading field in *Featuring → No Image → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[].feature_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_heading: prismic.RichTextField

  /**
   * Feature Description field in *Featuring → No Image → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField

  /**
   * Button Label field in *Featuring → No Image → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Featuring → No Image → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Alt field in *Featuring → No Image → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[].button_alt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_alt: prismic.KeyTextField
}

/**
 * Primary content in *Featuring → Default → Primary*
 */
export interface FeaturingSliceDefaultPrimary {
  /**
   * Heading field in *Featuring → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *Featuring → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Features field in *Featuring → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturingSliceDefaultPrimaryFeaturesItem>
  >
}

/**
 * Default variation for Featuring Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeaturingSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Featuring → No Image → Primary*
 */
export interface FeaturingSliceNoImagePrimary {
  /**
   * Heading field in *Featuring → No Image → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *Featuring → No Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Features field in *Featuring → No Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featuring.noImage.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturingSliceNoImagePrimaryFeaturesItem>
  >
}

/**
 * No Image variation for Featuring Slice
 *
 * - **API ID**: `noImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturingSliceNoImage = prismic.SharedSliceVariation<
  'noImage',
  Simplify<FeaturingSliceNoImagePrimary>,
  never
>

/**
 * Slice variation for *Featuring*
 */
type FeaturingSliceVariation = FeaturingSliceDefault | FeaturingSliceNoImage

/**
 * Featuring Shared Slice
 *
 * - **API ID**: `featuring`
 * - **Description**: Featuring
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturingSlice = prismic.SharedSlice<
  'featuring',
  FeaturingSliceVariation
>

/**
 * Primary content in *FooterElement → Default → Primary*
 */
export interface FooterElementSliceDefaultPrimary {
  /**
   * Layout field in *FooterElement → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_element.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  layout: prismic.ContentRelationshipField<'footer'>
}

/**
 * Default variation for FooterElement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterElementSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterElementSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FooterElement*
 */
type FooterElementSliceVariation = FooterElementSliceDefault

/**
 * FooterElement Shared Slice
 *
 * - **API ID**: `footer_element`
 * - **Description**: FooterElement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterElementSlice = prismic.SharedSlice<
  'footer_element',
  FooterElementSliceVariation
>

/**
 * Item in *FooterLogo → Default → Primary → Buttons*
 */
export interface FooterLogoSliceDefaultPrimaryButtonsItem {
  /**
   * Accessibility Text field in *FooterLogo → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.buttons[].accessibility_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accessibility_text: prismic.KeyTextField

  /**
   * Button Link field in *FooterLogo → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Icon field in *FooterLogo → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.buttons[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'envelope' | 'telephone'>
}

/**
 * Primary content in *FooterLogo → Default → Primary*
 */
export interface FooterLogoSliceDefaultPrimary {
  /**
   * Logo field in *FooterLogo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Buttons field in *FooterLogo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<FooterLogoSliceDefaultPrimaryButtonsItem>
  >

  /**
   * CTA Label field in *FooterLogo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField

  /**
   * CTA Link field in *FooterLogo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField
}

/**
 * Default variation for FooterLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLogoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterLogoSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FooterLogo*
 */
type FooterLogoSliceVariation = FooterLogoSliceDefault

/**
 * FooterLogo Shared Slice
 *
 * - **API ID**: `footer_logo`
 * - **Description**: FooterLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLogoSlice = prismic.SharedSlice<
  'footer_logo',
  FooterLogoSliceVariation
>

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Button Label field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What the button says
   * - **API ID Path**: hero.default.primary.buttons[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where the button goes
   * - **API ID Path**: hero.default.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Style field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'
  >
}

/**
 * Item in *Hero → Content Height → Primary → Buttons*
 */
export interface HeroSliceContentHeightPrimaryButtonsItem {
  /**
   * Button Label field in *Hero → Content Height → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What the button says
   * - **API ID Path**: hero.contentHeight.primary.buttons[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Hero → Content Height → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where the button goes
   * - **API ID Path**: hero.contentHeight.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Style field in *Hero → Content Height → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.contentHeight.primary.buttons[].button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'
  >
}

/**
 * Item in *Hero → With Image → Primary → Buttons*
 */
export interface HeroSliceWithImagePrimaryButtonsItem {
  /**
   * Button Label field in *Hero → With Image → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What the button says
   * - **API ID Path**: hero.withImage.primary.buttons[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Hero → With Image → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where the button goes
   * - **API ID Path**: hero.withImage.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Style field in *Hero → With Image → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.buttons[].button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'
  >
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the main hero text
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Sub Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Hero → Content Height → Primary*
 */
export interface HeroSliceContentHeightPrimary {
  /**
   * Heading field in *Hero → Content Height → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the main hero text
   * - **API ID Path**: hero.contentHeight.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Sub Heading field in *Hero → Content Height → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.contentHeight.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField

  /**
   * Buttons field in *Hero → Content Height → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.contentHeight.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<HeroSliceContentHeightPrimaryButtonsItem>
  >

  /**
   * Image field in *Hero → Content Height → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.contentHeight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Content Height variation for Hero Slice
 *
 * - **API ID**: `contentHeight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceContentHeight = prismic.SharedSliceVariation<
  'contentHeight',
  Simplify<HeroSliceContentHeightPrimary>,
  never
>

/**
 * Primary content in *Hero → With Image → Primary*
 */
export interface HeroSliceWithImagePrimary {
  /**
   * Heading field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the main hero text
   * - **API ID Path**: hero.withImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Sub Heading field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField

  /**
   * Buttons field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceWithImagePrimaryButtonsItem>>

  /**
   * Image field in *Hero → With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * With Image variation for Hero Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithImage = prismic.SharedSliceVariation<
  'withImage',
  Simplify<HeroSliceWithImagePrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceContentHeight
  | HeroSliceWithImage

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Item in *ImageWithText → Default → Primary → Buttons*
 */
export interface ImageWithTextSliceDefaultPrimaryButtonsItem {
  /**
   * Button Label field in *ImageWithText → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.buttons[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *ImageWithText → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Style field in *ImageWithText → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image_with_text.default.primary.buttons[].button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link',
    'filled'
  >
}

/**
 * Item in *ImageWithText → Right Image → Primary → Buttons*
 */
export interface ImageWithTextSliceRightImagePrimaryButtonsItem {
  /**
   * Button Label field in *ImageWithText → Right Image → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.buttons[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *ImageWithText → Right Image → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Button Style field in *ImageWithText → Right Image → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image_with_text.rightImage.primary.buttons[].button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link',
    'filled'
  >
}

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Background field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField

  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Heading field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Left List field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.left_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  left_list: prismic.RichTextField

  /**
   * Right List field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.right_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_list: prismic.RichTextField

  /**
   * Buttons field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<ImageWithTextSliceDefaultPrimaryButtonsItem>
  >
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ImageWithText → Right Image → Primary*
 */
export interface ImageWithTextSliceRightImagePrimary {
  /**
   * Background field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.rightImage.primary.background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  background: prismic.BooleanField

  /**
   * Image field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Heading field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Left List field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.left_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  left_list: prismic.RichTextField

  /**
   * Right List field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.right_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_list: prismic.RichTextField

  /**
   * Buttons field in *ImageWithText → Right Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.rightImage.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<ImageWithTextSliceRightImagePrimaryButtonsItem>
  >
}

/**
 * Right Image variation for ImageWithText Slice
 *
 * - **API ID**: `rightImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceRightImage = prismic.SharedSliceVariation<
  'rightImage',
  Simplify<ImageWithTextSliceRightImagePrimary>,
  never
>

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation =
  | ImageWithTextSliceDefault
  | ImageWithTextSliceRightImage

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  'image_with_text',
  ImageWithTextSliceVariation
>

/**
 * Item in *LinkList → Default → Primary → Links*
 */
export interface LinkListSliceDefaultPrimaryLinksItem {
  /**
   * Label field in *LinkList → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *LinkList → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *LinkList → Default → Primary*
 */
export interface LinkListSliceDefaultPrimary {
  /**
   * Heading field in *LinkList → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Links field in *LinkList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<LinkListSliceDefaultPrimaryLinksItem>>
}

/**
 * Default variation for LinkList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LinkListSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *LinkList*
 */
type LinkListSliceVariation = LinkListSliceDefault

/**
 * LinkList Shared Slice
 *
 * - **API ID**: `link_list`
 * - **Description**: LinkList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkListSlice = prismic.SharedSlice<
  'link_list',
  LinkListSliceVariation
>

/**
 * Primary content in *MapWithDetails → Default → Primary*
 */
export interface MapWithDetailsSliceDefaultPrimary {
  /**
   * Details field in *MapWithDetails → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map_with_details.default.primary.details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField

  /**
   * Map Url field in *MapWithDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map_with_details.default.primary.map_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  map_url: prismic.KeyTextField
}

/**
 * Default variation for MapWithDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapWithDetailsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MapWithDetailsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MapWithDetails*
 */
type MapWithDetailsSliceVariation = MapWithDetailsSliceDefault

/**
 * MapWithDetails Shared Slice
 *
 * - **API ID**: `map_with_details`
 * - **Description**: MapWithDetails
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapWithDetailsSlice = prismic.SharedSlice<
  'map_with_details',
  MapWithDetailsSliceVariation
>

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Label field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *MenuItem → With Sub Menu → Primary*
 */
export interface MenuItemSliceWithSubMenuPrimary {
  /**
   * Label field in *MenuItem → With Sub Menu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withSubMenu.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Sub Menu field in *MenuItem → With Sub Menu → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withSubMenu.primary.sub_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu: prismic.ContentRelationshipField<'sub_menu'>
}

/**
 * With Sub Menu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  'withSubMenu',
  Simplify<MenuItemSliceWithSubMenuPrimary>,
  never
>

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  'menu_item',
  MenuItemSliceVariation
>

/**
 * Item in *Process → Default → Primary → Steps*
 */
export interface ProcessSliceDefaultPrimaryStepsItem {
  /**
   * Icon field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'form' | 'call' | 'calendar' | 'comment'>

  /**
   * Step Title field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].step_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_title: prismic.TitleField

  /**
   * Description field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Label field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField

  /**
   * Button Link field in *Process → Default → Primary → Steps*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField
}

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Title field in *Process → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Heading field in *Process → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Steps field in *Process → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<ProcessSliceDefaultPrimaryStepsItem>>
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProcessSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Process
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessSlice = prismic.SharedSlice<'process', ProcessSliceVariation>

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Rich Text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichTextSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *RichText → Secondary → Primary*
 */
export interface RichTextSliceSecondaryPrimary {
  /**
   * Rich Text field in *RichText → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.secondary.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField
}

/**
 * Secondary variation for RichText Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceSecondary = prismic.SharedSliceVariation<
  'secondary',
  Simplify<RichTextSliceSecondaryPrimary>,
  never
>

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault | RichTextSliceSecondary

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  'rich_text',
  RichTextSliceVariation
>

/**
 * Item in *ServiceTarget → Default → Primary → Targets*
 */
export interface ServiceTargetSliceDefaultPrimaryTargetsItem {
  /**
   * Target Title field in *ServiceTarget → Default → Primary → Targets*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_target.default.primary.targets[].target_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  target_title: prismic.TitleField

  /**
   * Target Image field in *ServiceTarget → Default → Primary → Targets*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_target.default.primary.targets[].target_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  target_image: prismic.ImageField<never>

  /**
   * Target Description field in *ServiceTarget → Default → Primary → Targets*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_target.default.primary.targets[].target_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  target_description: prismic.RichTextField

  /**
   * Issue List field in *ServiceTarget → Default → Primary → Targets*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_target.default.primary.targets[].issue_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  issue_list: prismic.RichTextField
}

/**
 * Primary content in *ServiceTarget → Default → Primary*
 */
export interface ServiceTargetSliceDefaultPrimary {
  /**
   * Targets field in *ServiceTarget → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_target.default.primary.targets[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  targets: prismic.GroupField<
    Simplify<ServiceTargetSliceDefaultPrimaryTargetsItem>
  >
}

/**
 * Default variation for ServiceTarget Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceTargetSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServiceTargetSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ServiceTarget*
 */
type ServiceTargetSliceVariation = ServiceTargetSliceDefault

/**
 * ServiceTarget Shared Slice
 *
 * - **API ID**: `service_target`
 * - **Description**: ServiceTarget
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceTargetSlice = prismic.SharedSlice<
  'service_target',
  ServiceTargetSliceVariation
>

/**
 * Primary content in *SubMenuHeading → Default → Primary*
 */
export interface SubMenuHeadingSliceDefaultPrimary {
  /**
   * Heading field in *SubMenuHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_heading.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Default variation for SubMenuHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuHeadingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubMenuHeadingSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SubMenuHeading*
 */
type SubMenuHeadingSliceVariation = SubMenuHeadingSliceDefault

/**
 * SubMenuHeading Shared Slice
 *
 * - **API ID**: `sub_menu_heading`
 * - **Description**: SubMenuHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuHeadingSlice = prismic.SharedSlice<
  'sub_menu_heading',
  SubMenuHeadingSliceVariation
>

/**
 * Primary content in *SubMenuItem → Default → Primary*
 */
export interface SubMenuItemSliceDefaultPrimary {
  /**
   * Label field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for SubMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubMenuItemSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *SubMenuItem → Box → Primary*
 */
export interface SubMenuItemSliceBoxPrimary {
  /**
   * Label field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Description field in *SubMenuItem → Box → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.box.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Box variation for SubMenuItem Slice
 *
 * - **API ID**: `box`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceBox = prismic.SharedSliceVariation<
  'box',
  Simplify<SubMenuItemSliceBoxPrimary>,
  never
>

/**
 * Slice variation for *SubMenuItem*
 */
type SubMenuItemSliceVariation = SubMenuItemSliceDefault | SubMenuItemSliceBox

/**
 * SubMenuItem Shared Slice
 *
 * - **API ID**: `sub_menu_item`
 * - **Description**: SubMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSlice = prismic.SharedSlice<
  'sub_menu_item',
  SubMenuItemSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ClinicianDocument,
      ClinicianDocumentData,
      ClinicianDocumentDataFocusesItem,
      ClinicianDocumentDataApproachesItem,
      ClinicianDocumentDataServicesItem,
      ClinicianDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocumentDataSlices1Slice,
      FooterDocumentDataSlices2Slice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      LayoutDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SubMenuDocument,
      SubMenuDocumentData,
      SubMenuDocumentDataSlicesSlice,
      SubMenuDocumentDataSlices1Slice,
      SubMenuDocumentDataSlices2Slice,
      AllDocumentTypes,
      ContactInfoSlice,
      ContactInfoSliceDefaultPrimary,
      ContactInfoSliceVariation,
      ContactInfoSliceDefault,
      ContentIndexSlice,
      ContentIndexSliceDefaultPrimary,
      ContentIndexSliceVariation,
      ContentIndexSliceDefault,
      FeaturingSlice,
      FeaturingSliceDefaultPrimaryFeaturesItem,
      FeaturingSliceDefaultPrimary,
      FeaturingSliceNoImagePrimaryFeaturesItem,
      FeaturingSliceNoImagePrimary,
      FeaturingSliceVariation,
      FeaturingSliceDefault,
      FeaturingSliceNoImage,
      FooterElementSlice,
      FooterElementSliceDefaultPrimary,
      FooterElementSliceVariation,
      FooterElementSliceDefault,
      FooterLogoSlice,
      FooterLogoSliceDefaultPrimaryButtonsItem,
      FooterLogoSliceDefaultPrimary,
      FooterLogoSliceVariation,
      FooterLogoSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceContentHeightPrimaryButtonsItem,
      HeroSliceContentHeightPrimary,
      HeroSliceWithImagePrimaryButtonsItem,
      HeroSliceWithImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceContentHeight,
      HeroSliceWithImage,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimaryButtonsItem,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceRightImagePrimaryButtonsItem,
      ImageWithTextSliceRightImagePrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      ImageWithTextSliceRightImage,
      LinkListSlice,
      LinkListSliceDefaultPrimaryLinksItem,
      LinkListSliceDefaultPrimary,
      LinkListSliceVariation,
      LinkListSliceDefault,
      MapWithDetailsSlice,
      MapWithDetailsSliceDefaultPrimary,
      MapWithDetailsSliceVariation,
      MapWithDetailsSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceWithSubMenuPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      ProcessSlice,
      ProcessSliceDefaultPrimaryStepsItem,
      ProcessSliceDefaultPrimary,
      ProcessSliceVariation,
      ProcessSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceSecondaryPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      RichTextSliceSecondary,
      ServiceTargetSlice,
      ServiceTargetSliceDefaultPrimaryTargetsItem,
      ServiceTargetSliceDefaultPrimary,
      ServiceTargetSliceVariation,
      ServiceTargetSliceDefault,
      SubMenuHeadingSlice,
      SubMenuHeadingSliceDefaultPrimary,
      SubMenuHeadingSliceVariation,
      SubMenuHeadingSliceDefault,
      SubMenuItemSlice,
      SubMenuItemSliceDefaultPrimary,
      SubMenuItemSliceBoxPrimary,
      SubMenuItemSliceVariation,
      SubMenuItemSliceDefault,
      SubMenuItemSliceBox,
    }
  }
}
