// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  contact_info: dynamic(() => import('./ContactInfo')),
  content_index: dynamic(() => import('./ContentIndex')),
  featuring: dynamic(() => import('./Featuring')),
  footer_element: dynamic(() => import('./FooterElement')),
  footer_logo: dynamic(() => import('./FooterLogo')),
  frequently_asked_questions: dynamic(
    () => import('./FrequentlyAskedQuestions'),
  ),
  hero: dynamic(() => import('./Hero')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  link_list: dynamic(() => import('./LinkList')),
  map_with_details: dynamic(() => import('./MapWithDetails')),
  menu_item: dynamic(() => import('./MenuItem')),
  process: dynamic(() => import('./Process')),
  rich_text: dynamic(() => import('./RichText')),
  service_target: dynamic(() => import('./ServiceTarget')),
  sub_menu_heading: dynamic(() => import('./SubMenuHeading')),
  sub_menu_item: dynamic(() => import('./SubMenuItem')),
}
